name: almaworks
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.4.0
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  firebase_core: ^4.0.0
  logger: ^2.6.1
  firebase_storage: ^13.0.0
  path_provider: ^2.1.5
  dio: ^5.9.0
  path: ^1.9.1
  mime: ^2.0.0
  file_picker: ^10.2.4
  syncfusion_flutter_pdfviewer: ^30.2.4
  google_fonts: ^6.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  txt_docx: ^2.0.0
  signature: ^5.5.0
  docx_template: ^0.4.0
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0
  universal_html: ^2.2.4
  share_plus: ^11.1.0
  photo_view: ^0.15.0
  image: ^4.3.0
  flutter_zoom_drawer: ^3.2.0
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.5
  flutter_inappwebview_platform_interface: ^1.3.0+1
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^7.0.0
  open_file: ^3.5.10
  web: ^1.1.1
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  flutter_ringtone_player: ^4.0.0+4
  flutter_local_notifications: ^19.5.0
  elegant_notification: ^2.5.1
  timezone: ^0.10.1
  workmanager: ^0.9.0+3
  awesome_notifications: ^0.10.1
  firebase_auth: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"